name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install build-essential cmake
      run: sudo apt install build-essential cmake lcov doxygen libkgraphviewer2
    - name: install gtest
      run: |
          echo "Installing libgtest-dev"
          sudo apt-get install libgtest-dev
          echo "cd to usr/src/gtest"
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          echo "cp compiled gtest files to /usr/lib"
          sudo cp *.a /usr/lib
          echo "cd back to home dir"
          cd ~
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: make
      run: make
    - name: make test
      run: make test
    - name: get code coverage
      run: |
          cd tests/
          g++ -o main -g -fprofile-arcs -ftest-coverage -L /usr/lib -I/usr/include main_test.cpp -lgtest -lpthread
          ./main
          gcov main_test.cpp
          mkdir -p code_coverage
          lcov --directory . --capture --output-file ./code_coverage/code_coverage.info -rc lcov_branch_coverage=1
          genhtml code_coverage/code_coverage.info --output-directory code_coverage
    - name: make doc
      run: make doc
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: csvfile_main
        path: ./csvfile_main
    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: ./tests/code_coverage
